export const PLAN_LIMITS = {
  free: {
    max_repos: 1,
    scan_frequency: "weekly",
    ai_explanations: true,
    slopsquatting: false,
    one_click_pr: false,
    soc2_report: false,
    slack_alerts: false,
    email_alerts: false,
    trend_chart: false,
  },
  pro: {
    max_repos: Infinity,
    scan_frequency: "on_push",
    ai_explanations: true,
    slopsquatting: true,
    one_click_pr: true,
    soc2_report: false,
    slack_alerts: false,
    email_alerts: true,
    trend_chart: true,
  },
  team: {
    max_repos: Infinity,
    scan_frequency: "on_push_and_pr",
    ai_explanations: true,
    slopsquatting: true,
    one_click_pr: true,
    soc2_report: true,
    slack_alerts: true,
    email_alerts: true,
    trend_chart: true,
  },
  enterprise: {
    max_repos: Infinity,
    scan_frequency: "on_push_and_pr",
    ai_explanations: true,
    slopsquatting: true,
    one_click_pr: true,
    soc2_report: true,
    slack_alerts: true,
    email_alerts: true,
    trend_chart: true,
  },
} as const;
